# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Theme Jekyll Knacss 
baseline: Jekyll-Accessibility Knacss
description: Un thème jekyll basé sur Knacss avec une pointe d'accessibilité 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
locale: fr # the primary language of your content
twitter_username: uxlco0

# Build settings
markdown: kramdown